### ISSUE TITLE
hỏi đáp

### ISSUE THREAD

**Issue by nhathoang0110** [ThanhNguyenFG/Masked-Face-Detection#3]
Em chào anh ạ. Em được biết a có dùng dataset MAFA. Không biết em có thể xin face annotations của data này ko ạ. Trên baidu em không tải về được. Em cảm ơn ạ. Em không biết liên hệ kiểu gì nên đành comment ở đây.
đây là mail của em: nhathoangdk42@gmai.com
Em cảm ơn ạ

**Comment by ThanhNguyenFG** [comment]
Chị chào em :D, 
Em có thể dùng các file .zip từ link GoogleDrive nha, 2 file face annotations cũng có trong Drive luôn đó.

**Comment by nhathoang0110** [comment]
Dạ chị ạ :))).e cảm ơn ạ.Em cứ nghĩ là nó khác ạ.E cảm ơn ạ

Vào 18:29, T.5, 28 Th5, 2020 Nguyễn Phan Khiết Thanh <
notifications@github.com> đã viết:
